### ISSUE TITLE
id Confusion

### ISSUE THREAD

**Issue by eduardocereto** [zguillez/analytics-element#1]
This component seems to use the same id for the create method and for the &uid. These are completely different Ids. 
- the one used on create should be a webProperty Id of the form UA-XXXXX-Y, this is the analytics property that the data goes to.
- The &uid should be a userId and only set when the user is logged in. This should be a non-pii id that is unique for the user.

Setting &uid the same for all users can impact negatively the metrics for a site.

**Comment by eduardocereto** [comment]
Just realized this component is brand new, I'm not even sure how I ended up here

**Comment by zguillez** [comment]
Hi Edu
I replace the analytics param id to uid
Thanks

**Comment by eduardocereto** [comment]
I think you missed the point. The 2 IDs are completely different things.
They are not supposed to have the same value.

**Comment by zguillez** [comment]
Hi++
This is fixed now ;)
thanks
